### ISSUE TITLE
アプリの言語変更

### ISSUE THREAD

**Issue by ryota-hasegawa** [takusan23/TatimiDroid#1]
設定からアプリの言語を変更できるようにするのはどうでしょうか

**Comment by takusan23** [comment]
遅れてしまってごめんなさい。
少し書き足せば言語変更機能を追加できそうです。
あまり使わなそうですが、欲しければ付けたいと思います🥳

**Comment by ryota-hasegawa** [comment]
返信ありがとうございます。
Androidの言語を英語に設定しているのですが、ニコニコのアプリだけは日本語で表示したいなと思ったのでissueを開かせてもらいました。
意味のわからない理由だと思いますが、可能でしたらお願いします。

**Comment by takusan23** [comment]
なるほど。やってみますね

**Comment by ryota-hasegawa** [comment]
ありがとうございます
