### ISSUE TITLE
動画のモバイルデータのときの画質設定

### ISSUE THREAD

**Issue by Hinaxnitro** [takusan23/TatimiDroid#3]
動画の設定の モバイルデータのときは最低画質で再生 の項目をオンにすると

_問題が発生しました。
java.lang.NullPointerException_

というエラーが表示され動画が再生されません。

ベータ版を使用しています。

**Comment by takusan23** [comment]
報告ありがとうこざいます。確かに再生できないですね。
直せたので、次の更新までちょっとまっててください🥳

**Comment by Hinaxnitro** [comment]
ありがとうございます。
