### ISSUE TITLE
連続再生かつ一時停止中に途中で飛ばしたあとの動画のコメントの不具合

### ISSUE THREAD

**Issue by Hinaxnitro** [takusan23/TatimiDroid#4]
動画を連続再生していて _一時停止している_ 途中で飛ばしたときに

1. 動画は再生されますが、 コメントなどが一時停止したままになってしまいます。
2. (一時停止を解除したあとに)今見ている動画のコメントが表示されず、その前に見ていた動画のコメントが表示されてしまいます。

_2番目_の例です。(順番が異なりすいません。)
![Screenshot_20210404-220607](https://user-images.githubusercontent.com/72604007/113509696-082f1800-9592-11eb-8c57-440deaceb8d4.png)

**Comment by Hinaxnitro** [comment]
1番目の例です。
![Screenshot_20210404-223240](https://user-images.githubusercontent.com/72604007/113510461-e172e080-9595-11eb-90a3-ea8b6f3943d0.png)

**Comment by takusan23** [comment]
私の手元でも不具合を再現することが出来ました。

**Comment by takusan23** [comment]
とりあえずベータ版として公開しました。
リリース版は時間があるときに公開したいと思います。

**Comment by Hinaxnitro** [comment]
確認できました。
ありがとうございます。
